using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Accendo.DynamicsIntegration.Crm2015.Enums
{
    public enum CrmConditionTypeXml
    {
        Eq,
        Neq,
        Ne,
        Gt,
        Ge,
        Le,
        Lt,
        Like,
        NotLike,
        In,
        NotIn,
        Between,
        NotBetween,
        IsNull,
        NotNull,
        Yesterday,
        Today,
        Tomorrow,
        LastSevenDays,
        NextSevenDays,
        LastWeek,
        ThisWeek,
        NextWeek,
        LastMonth,
        ThisMonth,
        NextMonth,
        On,
        OnOrBefore,
        OnOrAfter,
        LastYear,
        ThisYear,
        NextYear,
        LastXHours,
        NextXHours,
        LastXDays,
        NextXDays,
        LastXWeeks,
        NextXWeeks,
        LastXMonths,
        NextXMonths,
        OlderthanXMonths,
        LastXYears,
        NextXYears,
        EqUserid,
        NeUserid,
        EqUserteams,
        EqBusinessid,
        NeBusinessid,
        EqUserlanguage,
        ThisFiscalYear,
        ThisFiscalPeriod,
        NextFiscalYear,
        NextFiscalPeriod,
        LastFiscalYear,
        LastFiscalPeriod,
        LastXFiscalYears,
        LastXFiscalPeriods,
        NextXFiscalYears,
        NextXFiscalPeriods,
        InFiscalYear,
        InFiscalPeriod,
        InFiscalPeriodAndYear,
        InOrBeforeFiscalPeriodAndYear,
        InOrAfterFiscalPeriodAndYear,
        BeginsWith,
        NotBeginWith,
        EndsWith,
        NotEndWith
    }
}
